frontend/fin_frontend/views/statements/views.py
from datetime import datetime, timedelta

import requests
from flask import Blueprint, current_app, redirect, render_template, url_for

from fin_frontend.decorators import extends_base_html
from fin_frontend.forms import build_forms
from fin_frontend.forms.accounts_form import SubmitForm
from fin_frontend.utils import (
    external_api_url_for,
    first_of_month,
    format_balance,
    get_next_quarter,
    get_quarter,
    prettify_flows,
)

statements_view = Blueprint(
    "statements",
    __name__,
    url_prefix="/statements",
    template_folder="templates",
    static_folder="static",
)


def get_api_data(endpoint, params=None):
    api_url = f"{external_api_url_for(endpoint)}"
    response = requests.get(api_url, params=params)
    response.raise_for_status()
    return response.json()


@statements_view.route("")
def main():
    return redirect(url_for("statements.balance_sheet"))


@statements_view.route("/balance_sheet", methods=["GET", "POST"])
@extends_base_html
def balance_sheet(base_params):
    _, quarter_form = build_forms("quarter")

    params = {}
    if quarter_form.update.data:
        params["year"] = quarter_form.year.data
        params["quarter"] = quarter_form.quarter.data

        quarter_begin = datetime(
            int(quarter_form.year.data),
            (int(quarter_form.quarter.data) - 1) * 3 + 1,
            1,
            0,
            0,
            0,
        )
        next_quarter_start = get_next_quarter(quarter_begin)
    else:
        quarter_begin, quarter_end = get_quarter()
        next_quarter_start = quarter_end + timedelta(milliseconds=2)

    balance_sheet_data = get_api_data("balance_sheet", params)

    submit_form = SubmitForm()
    submit_form.submit.label.text = "Perform Close on Date"
    submit_form.on_date.data = first_of_month()

    if submit_form.submit.data:
        close_date = submit_form.on_date.data.strftime("%Y-%m-%d")
        api_url = external_api_url_for("close")
        try:
            response = requests.post(api_url, json={"date": close_date})
            response.raise_for_status()
            return redirect(url_for("statements.balance_sheet"))
        except requests.HTTPError:
            error_message = "An error occurred while performing the close operation."
            try:
                error_data = response.json()
                if "error" in error_data:
                    error_message = error_data["error"]
            except ValueError:
                pass
            current_app.logger.error(f"HTTP error during close operation: {error_message}")

    header = (
        "Accounts",
        next_quarter_start.strftime("%B %d, %Y"),
        quarter_begin.strftime("%B %d, %Y"),
    )
    display_cash_assets = [
        (
            cash_asset["account_human_name"],
            format_balance(cash_asset["current_balance"], False),
            format_balance(cash_asset["previous_balance"], False),
        )
        for cash_asset in balance_sheet_data["assets"]["cash_assets"]
    ]
    cash_assets_total = (
        "Cash Assets",
        format_balance(sum([b["current_balance"] for b in balance_sheet_data["assets"]["cash_assets"]]), True),
        format_balance(sum([b["previous_balance"] for b in balance_sheet_data["assets"]["cash_assets"]]), True),
    )
    display_liquid_assets = [
        (
            liquid_asset["account_human_name"],
            format_balance(liquid_asset["current_balance"], False),
            format_balance(liquid_asset["previous_balance"], False),
        )
        for liquid_asset in balance_sheet_data["assets"]["noncash_liquid_assets"]
    ]
    liquid_assets_total = (
        "Noncash Liquid Assets",
        format_balance(
            sum([b["current_balance"] for b in balance_sheet_data["assets"]["noncash_liquid_assets"]]), True
        ),
        format_balance(
            sum([b["previous_balance"] for b in balance_sheet_data["assets"]["noncash_liquid_assets"]]), True
        ),
    )

    display_illiquid_assets = [
        (
            illiquid_asset["account_human_name"],
            format_balance(illiquid_asset["current_balance"], False),
            format_balance(illiquid_asset["previous_balance"], False),
        )
        for illiquid_asset in balance_sheet_data["assets"]["noncash_illiquid_assets"]
    ]
    illiquid_assets_total = (
        "Noncash Illiquid Assets",
        format_balance(
            sum([b["current_balance"] for b in balance_sheet_data["assets"]["noncash_illiquid_assets"]]), True
        ),
        format_balance(
            sum([b["previous_balance"] for b in balance_sheet_data["assets"]["noncash_illiquid_assets"]]), True
        ),
    )

    display_contra_assets = [
        (
            contra_asset["account_human_name"],
            format_balance(contra_asset["current_balance"], False),
            format_balance(contra_asset["previous_balance"], False),
        )
        for contra_asset in balance_sheet_data["assets"]["contra_assets"]
    ]
    contra_assets_total = (
        "Contra Assets",
        format_balance(sum([b["current_balance"] for b in balance_sheet_data["assets"]["contra_assets"]]), True),
        format_balance(sum([b["previous_balance"] for b in balance_sheet_data["assets"]["contra_assets"]]), True),
    )

    assets_total = (
        format_balance(balance_sheet_data["assets"]["total"]),
        format_balance(balance_sheet_data["assets"]["previous_total"]),
    )

    display_longterms = [
        (
            longterm_liability["account_human_name"],
            format_balance(longterm_liability["current_balance"], False),
            format_balance(longterm_liability["previous_balance"], False),
        )
        for longterm_liability in balance_sheet_data["liabilities"]["longterm_liabilities"]
    ]
    longterms_total = (
        "Longterm Liabilities",
        format_balance(
            sum([b["current_balance"] for b in balance_sheet_data["liabilities"]["longterm_liabilities"]]), True
        ),
        format_balance(
            sum([b["previous_balance"] for b in balance_sheet_data["liabilities"]["longterm_liabilities"]]), True
        ),
    )
    display_revolving = [
        (
            revolving_liability["account_human_name"],
            format_balance(revolving_liability["current_balance"], False),
            format_balance(revolving_liability["previous_balance"], False),
        )
        for revolving_liability in balance_sheet_data["liabilities"]["revolving_liabilities"]
    ]
    revolving_total = (
        "Revolving Liabilities",
        format_balance(
            sum([b["current_balance"] for b in balance_sheet_data["liabilities"]["revolving_liabilities"]]), True
        ),
        format_balance(
            sum([b["previous_balance"] for b in balance_sheet_data["liabilities"]["revolving_liabilities"]]), True
        ),
    )
    liabilities_total = (
        format_balance(balance_sheet_data["liabilities"]["total"]),
        format_balance(balance_sheet_data["liabilities"]["previous_total"]),
    )

    display_equities = [
        (
            equities["account_human_name"],
            format_balance(equities["current_balance"], False),
            format_balance(equities["previous_balance"], False),
        )
        for equities in balance_sheet_data["equity"]["accounts"]
    ]
    equity_total = (
        "Equity",
        format_balance(balance_sheet_data["equity"]["total"], True),
        format_balance(balance_sheet_data["equity"]["previous_total"], True),
    )

    equity_liabilities_total = (
        format_balance(balance_sheet_data["total_liabilities_and_equity"], True),
        format_balance(balance_sheet_data["total_previous_liabilities_and_equity"], True),
    )

    return render_template(
        "balance_sheet.html",
        header=header,
        quarter_form=quarter_form,
        display_cash_assets=display_cash_assets,
        cash_assets_total=cash_assets_total,
        display_liquid_assets=display_liquid_assets,
        liquid_assets_total=liquid_assets_total,
        display_illiquid_assets=display_illiquid_assets,
        illiquid_assets_total=illiquid_assets_total,
        display_contra_assets=display_contra_assets,
        contra_assets_total=contra_assets_total,
        total_assets=assets_total,
        display_longterm_liabilities=display_longterms,
        longterm_totals=longterms_total,
        display_revolving_liabilities=display_revolving,
        revolving_totals=revolving_total,
        total_liabilities=liabilities_total,
        display_equity=display_equities,
        equity_total=equity_total,
        equity_liab_total=equity_liabilities_total,
        submit_form=submit_form,
        **base_params,
    )


@statements_view.route("/income_statement", methods=["GET", "POST"])
@extends_base_html
def income_statement(base_params):
    _, quarter_form = build_forms("quarter")

    params = {}
    if quarter_form.update.data:
        params["year"] = quarter_form.year.data
        params["quarter"] = quarter_form.quarter.data

    statement = get_api_data("income_statement", params)

    # Gather everything for display
    revenues = [[name, format_balance(balance)] for name, balance in statement["revenues"].items()]
    gross_revenue = ["Gross Revenue", format_balance(statement["total_revenue"])]

    raw_op_expenses = statement["operating_expenses"]
    if len(raw_op_expenses) > 0:
        op_expenses = [[name, format_balance(-1 * abs(balance))] for name, balance in raw_op_expenses.items()]
    else:
        op_expenses = None

    op_profit = ["Operating Profit", format_balance(statement["operating_profit"])]

    raw_gains = statement["gains"]
    if len(raw_gains) > 0:
        display_gains = [[name, format_balance(balance)] for name, balance in raw_gains.items()]
    else:
        display_gains = None

    pre_tax_income = ["Income Before Tax", format_balance(statement["income_pre_tax"])]

frontend/fin_frontend/views/statements/templates/cash_flow_statement.html
{% extends "base.html" %}

{% block content %}
    <h1>Cash Flow Statement</h1>
    <Hr>
    <header class="main-header">
        <a href="{{ url_for('statements.balance_sheet')}}">Balance Sheet</a>
        <a href="{{ url_for('statements.income_statement')}}">Income Statement</a>
        <a href="{{ url_for('statements.cash_flow_statement')}}">Cash Flow Statement</a>
    </header>
    <Hr>

    <form action="{{ post_url }}" method="post" novalidate enctype="multipart/form-data">
        {{ quarter_form.hidden_tag() }}
        <div class="range-select-container">
            <label for="cash-flow-quarter-select">Year:</label>
            <div id="cash-flow-quarter-select" class="range-select"> {{ quarter_form.year(class="select-css") }} </div>
            <label for="cash-flow-quarter-select">Quarter:</label>
            <div id="cash-flow-quarter-select" class="range-select"> {{ quarter_form.quarter(class="select-css") }} </div>
            <div class="range-select"> {{ quarter_form.update(class="button") }} </div>
        </div>
    </form>

    <table>
        <tr>
            <td class="bordered-header income-statement-header">Cash Flows from Operations</td>
            <td class="bordered-header right-align-td"></td>
            <td class="bordered-header right-align-td"></td>
        </tr>
        {% for row in operating_activities %}
            <tr>
                <td class="bordered-cell income-statement-item">{{ row[0] }}</td>
                {% if loop.index == 1 %}
                <td class="bordered-cell right-align-td income-statement-expense">$</td>
                {% else %}
                <td class="bordered-cell right-align-td income-statement-expense"></td>
                {% endif %}
                <td class="bordered-cell right-align-td income-statement-expense">{{ row[1] }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td class="bordered-header income-statement-item" style="font-style: italic">{{ net_operating_activities[0] }}</td>
            <td class="bordered-header right-align-td income-statement-expense">$</td>
            <td class="bordered-header right-align-td">{{ net_operating_activities[1] }}</td>
        </tr>
        <tr>
            <td class="bordered-header income-statement-header">Cash Flows from Investment</td>
            <td class="bordered-header right-align-td income-statement-expense"></td>
            <td class="bordered-header right-align-td"></td>
        </tr>
        {% for row in investment_activities %}
            <tr>
                <td class="bordered-cell income-statement-item">{{ row[0] }}</td>
                {% if loop.index == 1 %}
                <td class="bordered-cell right-align-td income-statement-expense">$</td>
                {% else %}
                <td class="bordered-cell right-align-td income-statement-expense"></td>
                {% endif %}
                <td class="bordered-cell right-align-td income-statement-expense">{{ row[1] }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td class="bordered-header income-statement-item" style="font-style: italic">{{ net_investment_activities[0] }}</td>
            <td class="bordered-header right-align-td income-statement-expense">$</td>
            <td class="bordered-header right-align-td ">{{ net_investment_activities[1] }}</td>
        </tr>
        <tr>
            <td class="bordered-header income-statement-header">Cash Flows from Financing</td>
            <td class="bordered-header right-align-td income-statement-expense"></td>
            <td class="bordered-header right-align-td"></td>
        </tr>
        {% for row in financing_activities %}
            <tr>
                <td class="bordered-cell income-statement-item">{{ row[0] }}</td>
                {% if loop.index == 1 %}
                <td class="bordered-cell right-align-td income-statement-expense">$</td>
                {% else %}
                <td class="bordered-cell right-align-td income-statement-expense"></td>
                {% endif %}
                <td class="bordered-cell right-align-td income-statement-expense">{{ row[1] }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td class="bordered-header income-statement-item" style="font-style: italic">{{ net_financing_activities[0] }}</td>
            <td class="bordered-header right-align-td income-statement-expense">$</td>
            <td class="bordered-header right-align-td ">{{ net_financing_activities[1] }}</td>
        </tr>
        <tr>
            <td class="bordered-header income-statement-header">Net Cash Flows</td>
            <td class="bordered-header right-align-td income-statement-expense"></td>
            <td class="bordered-header right-align-td"></td>
        </tr>
        {% for row in net_cash %}
            <tr>
                <td class="bordered-cell income-statement-item">{{ row[0] }}</td>
                <td class="bordered-cell right-align-td income-statement-expense">$</td>
                <td class="bordered-cell right-align-td ">{{ row[1] }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

frontend/fin_frontend/views/statements/templates/income_statement.html
{% extends "base.html" %}

{% block content %}
<h1>Income Statement</h1>
    <Hr>
    <header class="main-header">
        <a href="{{ url_for('statements.balance_sheet')}}">Balance Sheet</a>
        <a href="{{ url_for('statements.income_statement')}}">Income Statement</a>
        <a href="{{ url_for('statements.cash_flow_statement')}}">Cash Flow Statement</a>
    </header>
    <Hr>

    <form action="{{ post_url }}" method="post" novalidate enctype="multipart/form-data">
        {{ quarter_form.hidden_tag() }}
        <div class="range-select-container">
            <label for="cash-flow-quarter-select">Year:</label>
            <div id="cash-flow-quarter-select" class="range-select"> {{ quarter_form.year(class="select-css") }} </div>
            <label for="cash-flow-quarter-select">Quarter:</label>
            <div id="cash-flow-quarter-select" class="range-select"> {{ quarter_form.quarter(class="select-css") }} </div>
            <div class="range-select"> {{ quarter_form.update(class="button") }} </div>
        </div>
    </form>

    <table>
        <tr>
            <td class="bordered-header income-statement-header">Revenues</td>
            <td class="bordered-header right-align-td"></td>
            <td class="bordered-header right-align-td"></td>
        </tr>
        {% if gross_revenue %}
            {% for row in revenues %}
            <tr>
                <td class="bordered-cell income-statement-item">{{ row[0] }}</td>
                {% if loop.index == 1 %}
                <td class="bordered-cell right-align-td income-statement-expense">$</td>
                {% else %}
                <td class="bordered-cell right-align-td income-statement-expense"></td>
                {% endif %}
                <td class="bordered-cell right-align-td income-statement-expense">{{ row[1] }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td class="bordered-header income-statement-header">Gross Revenue</td>
                <td class="bordered-header right-align-td income-statement-expense">$</td>
                <td class="bordered-header right-align-td">{{ gross_revenue[1] }}</td>
            </tr>
        {% endif %}
        {% if op_expenses %}
            <tr>
                <td class="bordered-header income-statement-header">Operating Expenses</td>
                <td class="bordered-header right-align-td"></td>
                <td class="bordered-header right-align-td"></td>
            </tr>
            {% for row in op_expenses %}
                <tr>
                    <td class="bordered-cell income-statement-item">{{ row[0] }}</td>
                    {% if loop.index == 1 %}
                    <td class="bordered-cell right-align-td income-statement-expense">$</td>
                    {% else %}
                    <td class="bordered-cell right-align-td income-statement-expense"></td>
                    {% endif %}
                    <td class="bordered-cell right-align-td income-statement-expense">{{ row[1] }}</td>
                </tr>
            {% endfor %}
        {% endif %}
        <tr>
            <td class="bordered-header income-statement-header">Operating Profit</td>
            <td class="bordered-header income-statement-expense right-align-td">$</td>
            <td class="bordered-header right-align-td">{{ op_profit[1] }}</td>
        </tr>
        {% if gains %}
        <tr>
            <td class="bordered-header income-statement-header">Financial Gains</td>
            <td class="bordered-header right-align-td"></td>
            <td class="bordered-header right-align-td"></td>
        </tr>
            {% for row in gains %}
                <tr>
                    <td class="bordered-cell income-statement-item">{{ row[0] }}</td>
                    {% if loop.index == 1 %}
                    <td class="bordered-cell right-align-td income-statement-expense">$</td>
                    {% else %}
                    <td class="bordered-cell right-align-td income-statement-expense"></td>
                    {% endif %}
                    <td class="bordered-cell right-align-td">{{ row[1] }}</td>
                </tr>
            {% endfor %}
        {% endif %}
        <tr>
            <td class="bordered-header income-statement-header">Pre-tax Income</td>
            <td class="bordered-header income-statement-expense right-align-td">$</td>
            <td class="bordered-header right-align-td">{{ pre_tax_income[1] }}</td>
        </tr>
        {% if cont_op_expenses %}
            <tr>
                <td class="bordered-header income-statement-header">Continued Operation Expenses</td>
                <td class="bordered-header right-align-td"></td>
                <td class="bordered-header right-align-td"></td>
            </tr>
            {% for row in cont_op_expenses %}
                <tr>
                    <td class="bordered-cell income-statement-item">{{ row[0] }}</td>
                    {% if loop.index == 1 %}
                    <td class="bordered-cell right-align-td income-statement-expense">$</td>
                    {% else %}
                    <td class="bordered-cell right-align-td income-statement-expense"></td>
                    {% endif %}
                    <td class="bordered-cell right-align-td income-statement-expense">{{ row[1] }}</td>
                </tr>
            {% endfor %}
        {% endif %}
        <tr>
            <td class="bordered-header income-statement-header">Income</td>
            <td class="bordered-header income-statement-expense right-align-td">$</td>
            <td class="bordered-header right-align-td">{{ income[1] }}</td>
        </tr>


    </table>
{% endblock %}

frontend/fin_frontend/views/statements/templates/statements_overview.html
{% extends "base.html" %}

{% block content %}
<h1>Statements</h1>
    <Hr>
    <header class="main-header">
        <a href="{{ url_for('statements.balance_sheet')}}">Balance Sheet</a>
        <a href="{{ url_for('statements.income_statement')}}">Income Statement</a>
        <a href="{{ url_for('statements.cash_flow_statement')}}">Cash Flow Statement</a>
    </header>
    <Hr>
{% endblock %}